version: "3.9"

services:
  # ================================= Bot =====================================
  # Generic Rasa bot, used to run console for example.
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    container_name: bot
    volumes:
      - ./bot/:/bot/
    ports:
      - 5005:5005
    depends_on:
      - actions
    networks:
      - bot

  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    container_name: actions
    ports:
      - 5055:5055
    volumes:
      - ./bot:/bot
    command: sh -c "python -m rasa_sdk --actions actions"
    networks:
      - bot

  # ============================ Webchat Page  =================================
  # A container to run webchat html page
  webchat:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./modules/webchat:/usr/share/nginx/html
    networks:
      - bot

  # ============================ Telegram Bot =================================
  # Specific Rasa bot integrated with Telegram.
  bot-telegram:
      build:
        context: .
        dockerfile: ./docker/bot.Dockerfile
      volumes:
        - ./bot/:/bot/
      env_file:
        - env/bot-telegram.env
      ports:
        - 5005:5005
      command: sh -c "make telegram"

networks:
  bot:
    driver: bridge
