name: Rasa Test PR

on:
  pull_request:
    branches:
      - main      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot/requirements.txt

    - name: Run Rasa Test
      run: |
        rasa test

    - name: Run Rasa Model Report
      run: |
        rasa train
        rasa model report
